export const INIT_ISSUES_DATA_REQUEST = 'INIT_ISSUES_DATA_REQUEST';
export const SET_ISSUES_DATA_ERROR = 'SET_ISSUES_DATA_ERROR';
export const SET_ISSUES_DATA_SUCCESS = 'SET_ISSUES_DATA_SUCCESS';
export const SET_ISSUES_DATA_INITIATED = 'SET_ISSUES_DATA_INITIATED';
